### ISSUE TITLE
cordova-wifiscanner plugin crashes Visual Studio 2013

### ISSUE THREAD

**Issue by samseth003** [nielsAD/cordova-wifiscanner#3]
![cordova-wifiscanner](https://cloud.githubusercontent.com/assets/10734133/5931065/222b4114-a6fd-11e4-8b9e-5f17280012e2.PNG)

**Comment by nielsAD** [comment]
Do you have any idea what could be causing this?

**Comment by samseth003** [comment]
I am not sure what caused the problem but I notice that when I try to install the other plugins (click the little button next to the URL as shown above), the information about Version, Plugin ID, Description, Platforms, License is shown and then I can add the plugins. However, no information is shown related to your plugin. When I click add, VS crashes. Maybe git doesn't host your plugin properly.
